ARG cuda_version=9.0
ARG cudnn_version=7
FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      libglib2.0-dev \
      wget && \
    rm -rf /var/lib/apt/lists/*



# Install conda
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN wget --quiet --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh && \
    echo "c59b3dd3cad550ac7596e0d599b91e75d88826db132e4146030ef471bb434e9a *Miniconda3-4.2.12-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash /Miniconda3-4.2.12-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-4.2.12-Linux-x86_64.sh && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh

# Install Python packages and keras
ENV NB_USER nbuser
ENV NB_UID 1000

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    chown $NB_USER $CONDA_DIR -R && \
    mkdir -p /src && \
    chown $NB_USER /src && \
    mkdir -p /dependencies && \
    chown $NB_USER /dependencies

RUN mkdir -p /dependencies/glibc
RUN cd /dependencies/glibc
RUN wget --quiet http://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.gz
RUN tar zxvf glibc-2.27.tar.gz
RUN cd glibc-2.27
RUN mkdir build
RUN ls
RUN configure
RUN cd build
RUN make -j4
RUN make install


USER $NB_USER

COPY tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl /src/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl

ARG python_version=3.6

RUN conda config --append channels conda-forge
RUN conda install -y python=${python_version} && \
    pip install --upgrade pip && \
    pip install /src/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl && \
    pip install \
      sklearn_pandas \
      cntk-gpu && \
    conda install \
      bcolz \
      h5py \
      matplotlib \
      mkl \
      nose \
      notebook \
      Pillow \
      pandas \
      pydot \
      pygpu \
      pyyaml \
      scikit-learn \
      six \
      theano \
      mkdocs \
      opencv \
      jupyterlab \
      tqdm \
      scikit-image \
      pillow \
      multiprocess \
      nibabel \
      scikit-learn \
      nipype \
      && \
    rm -rf /src/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl && \
    git clone git://github.com/keras-team/keras.git /src && pip install -e /src[tests] && \
    pip install git+git://github.com/keras-team/keras.git && \
    conda clean -yt
RUN conda install -c https://conda.anaconda.org/simpleitk SimpleITK
RUN export PATH=/usr/local/cuda-9.0/bin:$PATH
RUN export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64/:/usr/local/glibc-2.27/lib

ADD theanorc /home/keras/.theanorc
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
COPY jupyter_notebook_config.py /home/nbuser/jupyter_notebook_config.py
ENV PYTHONPATH='/src/:$PYTHONPATH'

WORKDIR /data

EXPOSE 8888

CMD jupyter notebook --port=8888 --config='/home/nbuser/jupyter_notebook_config.py'
